### ISSUE TITLE
Income sharing / distribution formula and backtest

### ISSUE THREAD

**Issue by hackable** [hackable/gpw#3]

**Comment by Abhi150688** [comment]
Query Ready. Need Postgress access to fine-tune & test it.

**Comment by Abhi150688** [comment]
select requserid, reqvirtualhost,count(*) as num, CAST (count(requserid) as Float)/Cast ((SUM (count(*)) OVER (Partition by requserid)) as Float) AS Ratio from logs group by requserid, reqvirtualhost order by num desc 

For Daily stats - Append where date like ' '
Same query with modifications to collate data over multiple days and compute daily incremental stats.
